const PRODUCTS = [
  {
    id: 'stop-akne',
    name: 'Бокс «Стоп акне»',
    price: 1990, old: 2990,
    sku: '4Y252D08',
    badge: 'Хит',
    tag: 'От акне, постакне, дерматита и купероза',
    cats: ['face', 'sets'],
    img: 'assets/products/stop-akne.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-761961080840-boks-stop-akne',
    contents: ['Крем ОЗОДЕРМИК 3% — 80 мл', 'Озонированное масло ОТРИ 25 мл'],
    benefits: ['Снимает воспаление за 21 день', 'Не сушит кожу', 'Без гормонов и антибиотиков']
  },
  {
    id: 'krem-pryschi',
    name: 'Лечебный крем против прыщей',
    price: 967, old: 1790,
    sku: '2G02',
    badge: 'Хит',
    tag: 'Точечное действие, убирает красноту',
    cats: ['face'],
    img: 'assets/products/krem-pryschi.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-231661081751-lechebnii-krem-protiv-prischei',
    contents: ['Тюбик 20 мл'],
    benefits: ['Работает точечно', 'Убирает красноту за ночь', 'Подходит с 12 лет']
  },
  {
    id: 'super-kombo',
    name: 'Набор «Супер комбо»',
    price: 4999, old: 8290,
    sku: 'SC1G051H054Y252D',
    badge: 'Хит',
    tag: 'Максимальный уход для преображения лица',
    cats: ['face', 'sets'],
    img: 'assets/products/super-kombo.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-820575897231-nabor-super-kombo',
    contents: ['Дневной и ночной кремы', 'Озодермик 3%', 'Масло ОТРИ'],
    benefits: ['Полный цикл ухода', 'Выгода 3 291 рубль', 'Хватает на 3 месяца']
  },
  {
    id: 'chistaya-kozha',
    name: 'Безупречно чистая кожа',
    price: 2800, old: 3990,
    sku: '1G051H05',
    badge: 'Бестселлер',
    tag: 'От морщин, пигментации и воспалений',
    cats: ['face', 'sets'],
    img: 'assets/products/chistaya-kozha.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-962922058658-bezuprechno-chistaya-kozha',
    contents: ['Дневной озоновый крем — 50 мл', 'Ночной крем глубокого действия — 50 мл'],
    benefits: ['Работает круглосуточно', 'Выравнивает тон', 'Накопительный эффект']
  },
  {
    id: 'super-trio',
    name: 'Набор «Супер трио»',
    price: 2893, old: 4380,
    sku: 'ST4Y252D',
    badge: 'Бестселлер',
    tag: 'Очищение и уход для проблемной кожи',
    cats: ['face', 'sets'],
    img: 'assets/products/super-trio.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-685815475881-nabor-super-trio',
    contents: ['Три средства для домашнего ухода'],
    benefits: ['Программа на месяц', 'Очищение плюс лечение', 'Экономия 1 487 рублей']
  },
  {
    id: 'super-duet',
    name: 'Подарочный набор «Супер дуэт»',
    price: 1976, old: 3180,
    sku: 'SD4Y252PP',
    badge: 'Бестселлер',
    tag: 'Для нормальной и проблемной кожи',
    cats: ['sets'],
    img: 'assets/products/super-duet.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-278619326611-podarochnii-nabor-super-duet',
    contents: ['Два средства в подарочной упаковке'],
    benefits: ['Готовый подарок', 'Подходит любому типу кожи', 'Выгода 1 204 рубля']
  },
  {
    id: 'ochischenie',
    name: 'Озоновое очищение',
    price: 1257, old: 1390,
    sku: 'OUDL1',
    badge: 'Бестселлер',
    tag: 'Озоновая эмульсия для лица',
    cats: ['face'],
    img: 'assets/products/ochischenie.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-613459663771-ozonovoe-ochischenie',
    contents: ['Тюбик 90 мл'],
    benefits: ['Мягкое очищение', 'Не нарушает барьер кожи', 'Первый шаг любого ухода']
  },
  {
    id: 'set-lico',
    name: 'Сет для лица',
    price: 4479, old: 6900,
    sku: '1G051H054Y252D08',
    badge: '-50%',
    tag: 'От прыщей, дерматита, купероза и морщин',
    cats: ['face', 'sets'],
    img: 'assets/products/set-lico.jpg',
    url: 'https://ozonbox.ru/instashop/tproduct/200054800-792766547281-set-dlya-litsa',
    contents: ['Набор «Безупречно чистая кожа»', 'Бокс «Стоп акне»'],
    benefits: ['Два набора по цене одного', 'Максимальная выгода', 'Уход на 3 месяца']
  },
  {
    id: 'otri-6000',
    name: 'Озонированное масло «Отри 6000»',
    price: 899, old: 1600,
    sku: '4X10',
    badge: 'Лечебное',
    tag: 'От прыщей, розацеа, воспалений и грибка',
    cats: ['face', 'oils'],
    img: 'assets/products/otri-6000.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-588807313791-ozonirovannoe-olivkovoe-maslo-otri-6000',
    contents: ['Оливковое масло, насыщенное озонидами'],
    benefits: ['Хватает на 6 месяцев', 'Сто процентов натуральный состав', 'Самая низкая цена в линейке']
  },
  {
    id: 'shampun',
    name: 'Лечебный шампунь «Озодермис»',
    price: 1205, old: 1500,
    sku: '2В20',
    badge: 'Новинка',
    tag: 'Против выпадения, перхоти и дерматита',
    cats: ['hair'],
    img: 'assets/products/shampun.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-245705284741-lechebnii-shampun-ozodermis-dlya-volos-i',
    contents: ['Тюбик 200 мл'],
    benefits: ['Лечит кожу головы', 'Останавливает выпадение', 'Без SLS и силиконов']
  },
  {
    id: 'maska-shampun',
    name: 'Набор маска и шампунь',
    price: 2352, old: 3500,
    sku: '2B202A15',
    badge: 'Новинка',
    tag: 'Интенсивное восстановление волос',
    cats: ['hair', 'sets'],
    img: 'assets/products/maska-shampun.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-286774130771-nabor-maska-shampun',
    contents: ['Шампунь 200 мл', 'Маска 150 мл'],
    benefits: ['Полный уход за волосами', 'Против перхоти и выпадения', 'Выгода 1 148 рублей']
  },
  {
    id: 'vosstanovlenie-volos',
    name: 'Полное восстановление волос',
    price: 2490, old: 3750,
    sku: '1A153A15',
    badge: '',
    tag: 'Защита, рост и восстановление структуры',
    cats: ['hair', 'sets'],
    img: 'assets/products/vosstanovlenie-volos.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-454701222522-polnoe-vosstanovlenie-volos',
    contents: ['Маска для структуры волос — 150 мл', 'Маска для роста — 150 мл'],
    benefits: ['Две маски разного действия', 'Виден результат за месяц', 'Для повреждённых волос']
  },
  {
    id: 'maska-volosy',
    name: 'Озодермик, маска для волос',
    price: 1306, old: 2000,
    sku: '2A15',
    badge: '',
    tag: 'От выпадения, перхоти, дерматита и псориаза',
    cats: ['hair'],
    img: 'assets/products/maska-volosy.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-356537185811-ozodermik-lechebnaya-maska-dlya-volos-i',
    contents: ['Тюбик 150 мл'],
    benefits: ['Лечебное действие', 'Успокаивает кожу головы', 'Подходит при псориазе']
  },
  {
    id: 'idealnoe-telo',
    name: 'Идеальное тело',
    price: 3500, old: 5990,
    sku: 'OB3',
    badge: '',
    tag: 'Комплексный уход за телом',
    cats: ['body', 'sets'],
    img: 'assets/products/idealnoe-telo.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-255795231031-idealnoe-telo',
    contents: ['Антицеллюлитный крем — 150 мл', 'Крем для ног — 150 мл', 'Озонированное масло — 25 мл'],
    benefits: ['Три средства в наборе', 'Против целлюлита и отёков', 'Выгода 2 490 рублей']
  },
  {
    id: 'anticellulit',
    name: 'Антицеллюлитный массажный крем',
    price: 1633, old: 2400,
    sku: '3Q15',
    badge: '',
    tag: 'Против целлюлита, отёков, растяжек и варикоза',
    cats: ['body'],
    img: 'assets/products/anticellulit.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-170225406601-antitsellyulitnii-massazhnii-krem',
    contents: ['Тюбик 150 мл'],
    benefits: ['Разогревающий эффект', 'Снимает отёки', 'Улучшает микроциркуляцию']
  },
  {
    id: 'sos-boks',
    name: 'Набор «СОС бокс»',
    price: 1900, old: 2490,
    sku: 'SB1',
    badge: '',
    tag: 'Экстренная помощь коже и волосам',
    cats: ['sets', 'hair'],
    img: 'assets/products/sos-boks.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-860204519016-nabor-sos-boks',
    contents: ['Маска для волос с озонидами — 150 мл', 'Крем ОЗОДЕРМИК 5% — 50 мл'],
    benefits: ['Быстрый результат', 'Усиленная формула', 'Два средства в наборе']
  },
  {
    id: 'ozodermik-3',
    name: 'Озодермик 3%',
    price: 1195, old: 1790,
    sku: '2D08',
    badge: '',
    tag: 'Крем от акне, постакне и купероза',
    cats: ['face'],
    img: 'assets/products/ozodermik-3.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-498754118681-ozodermik-3',
    contents: ['Тюбик 80 мл'],
    benefits: ['Базовая концентрация', 'Для ежедневного применения', 'Восстанавливает кожу']
  },
  {
    id: 'ozodermik-5',
    name: 'Озодермик 5%',
    price: 1303, old: 1400,
    sku: '2E050',
    badge: '',
    tag: 'Действие вдвое сильнее, чем у крема 3%',
    cats: ['face'],
    img: 'assets/products/ozodermik-5.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-141830412781-ozodermik-5',
    contents: ['Тюбик 50 мл'],
    benefits: ['Усиленная концентрация', 'Для запущенных случаев', 'Рекомендован с 12 лет']
  },
  {
    id: 'dnevnoy-krem',
    name: 'Дневной крем',
    price: 1419, old: 1900,
    sku: 'OB3',
    badge: '',
    tag: 'Увлажнение, питание, дневная защита',
    cats: ['face'],
    img: 'assets/products/dnevnoy-krem.jpg',
    url: 'https://ozonbox.ru/tproduct/199289486-752699317171-dnevnoi-krem',
    contents: ['Тюбик 50 мл'],
    benefits: ['Лёгкая текстура', 'Базовый дневной уход', 'Подходит под макияж']
  }
];

const CATEGORIES = [
  { id: 'all', label: 'Все товары' },
  { id: 'hit', label: 'Хиты' },
  { id: 'face', label: 'Лицо' },
  { id: 'hair', label: 'Волосы' },
  { id: 'body', label: 'Тело' },
  { id: 'sets', label: 'Наборы' }
];
